package by.epamtc.tsalko.controller.command;

public enum ParameterName {

    AUTHORIZATION,
    REGISTRATION,
    LOGOUT,
    APP_LOCALIZATION,

    GO_TO_PERSONAL_PAGE,
    GO_TO_PERSONAL_PAGE_ORDERS,
    GO_TO_PERSONAL_PAGE_DETAILS,
    GO_TO_PERSONAL_PAGE_PASSPORT,
    GO_TO_PERSONAL_PAGE_BANKCARDS,
    GO_TO_PERSONAL_PAGE_CREATE_BANKCARD,
    GO_TO_PERSONAL_PAGE_ALL_ORDERS,
    GO_TO_PERSONAL_PAGE_ALL_USERS,
    GO_TO_ALL_USER_DATA,
    GO_TO_CREATE_ORDER,
    GO_TO_PAYMENT_PAGE,
    UPDATE_USER_DETAILS,
    UPDATE_USER_PASSPORT,
    CREATE_BANKCARD,
    DELETE_BANKCARD,
    PAY_ORDER,
    GO_TO_MAIN_PAGE,
    GO_TO_LOGIN_PAGE,
    GO_TO_REGISTRATION_PAGE,
    GO_TO_CONTACT_PAGE,
    GO_TO_OUR_CARS,
    GO_TO_CAR_PAGE,
    GO_TO_NEWS,
    GO_TO_RULES,
    GO_TO_STOCKS,
    GO_TO_TEST_PAGE_500
}
