package by.epamtc.tsalko.controller.command;

public enum ParameterName {

    AUTHORIZATION,
    REGISTRATION,
    LOGOUT,
    APP_LOCALIZATION,

    GO_TO_USER_PAGE_ORDERS,
    GO_TO_USER_PAGE_PASSPORT,
    GO_TO_USER_PAGE_CARDS,
    GO_TO_USER_PAGE_ALL_ORDERS,
    GO_TO_MAIN_PAGE,
    GO_TO_LOGIN_PAGE,
    GO_TO_REGISTRATION_PAGE,
    GO_TO_CONTACT_PAGE,
    GO_TO_CATALOG,
    GO_TO_CAR_PAGE,
    GO_TO_NEWS,
    GO_TO_RULES,
    GO_TO_STOCKS
}
